---
# Uninstall Impala Server
- name: Stop Impala Server
  shell: maprcli node services -name impalaserver -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-impala-server
  package: name=mapr-impala-server state=absent
