---
# Is this a bug? It is not documented to do this.
- name: Get Fluentd version
  shell: cat /opt/mapr/fluentd/fluentdversion
  register: version_output
  check_mode: no
  changed_when: no
- name: Create CA dir
  file: path=/opt/mapr/fluentd/fluentd-{{ version_output.stdout }}/etc/fluentd/ca/ state=directory

- name: Copy PEM file to FluentD for secure ElasticSearch
  copy: src=/tmp/mapr_spyglass/es/sg/ca/es-root-ca.pem dest=/opt/mapr/fluentd/fluentd-{{ version_output.stdout }}/etc/fluentd/ca/es-root-ca.pem owner={{ mapr_user }} group={{ mapr_group }} mode=0600
# Workaround: Disable SSL cert check. For some reason validation always fails because of hostname.
- name: Workaround - Disable SSL cert check.
  lineinfile:  dest=/opt/mapr/fluentd/fluentd-{{ version_output.stdout }}/etc/fluentd/es_config.conf regexp='(.*)ssl_verify(.*)' line=" ssl_verify false"