---
# Copy JAR for MapR Spark YARN shuffle
- name: Find Spark Path
  find: paths="/opt/mapr/spark" patterns="spark*" file_type=directory
  register: spark_path_result
  failed_when: spark_path_result.matched != 1
- set_fact: spark_path="{{ spark_path_result.files[0].path }}"
- name: Find Spark Shuffle on first Spark Node
  find: paths="{{ spark_path }}/yarn/" patterns="spark-*-shuffle.jar" file_type=file
  register: shuffle_jar_path_result
  failed_when: shuffle_jar_path_result.matched != 1

- name: Fetch Spark Shuffle JAR
  fetch: src="{{ shuffle_jar_path_result.files[0].path }}" dest=/tmp/spark-yarn-shuffle.jar flat=yes
