---
# Install MapR elasticsearch
#- name: Find ElasticSearch Path
#  find: paths="/opt/mapr/elasticsearch/" patterns="elasticsearch*" file_type=directory
#  register: es_path_result
#  failed_when: es_path_result.matched != 1
- name: Get Elasticsearch version
  shell: cat /opt/mapr/elasticsearch/elasticsearchversion
  register: version_output
  check_mode: no
  changed_when: no
- name: Copy ElasticSearch files for Security
  copy: src=/tmp/mapr_spyglass/es/{{ item.src }} dest=/opt/mapr/elasticsearch/elasticsearch-{{ version_output.stdout }}/{{ item.dst }} owner={{ mapr_user }} group={{ mapr_group }} mode={{ item.mode }}
  with_items:
    - src: sg/ca/es-root-ca.pem
      dst: etc/elasticsearch/ca/
      mode: "0600"
    - src: sg/truststore.jks
      dst: etc/elasticsearch/keystores/
      mode: "0640"
    - src: sg/admin-usr-keystore.jks
      dst: etc/elasticsearch/keystores/
      mode: "0640"
    - src: sg/{{ ansible_fqdn }}-srvr-keystore.jks
      dst: etc/elasticsearch/keystores/
      mode: "0640"
    - src: sg/sg2.yml
      dst: etc/elasticsearch/
      mode: "0600"
    - src: sg/sg_http_{{ ansible_fqdn }}.yml
      dst: etc/elasticsearch/
      mode: "0600"
    - src: sg/sg_ssl_{{ ansible_fqdn }}.yml
      dst: etc/elasticsearch/
      mode: "0600"
    - src: .keystore_password
      dst: etc/elasticsearch/
      mode: "0600"
