---
# Configure unsecure cluster

- name: Configure.sh
  shell: /opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -unsecure -HS {{ historyserver_string }} {{ "--isvm" if virtual_machine else "" }}




