---
#- name: Find Kibana Path
#  find: paths="/opt/mapr/kibana/" patterns="kibana*" file_type=directory
#  register: kibana_path_result
#  failed_when: kibana_path_result.matched != 1
- name: Get Kibana version
  shell: cat /opt/mapr/kibana/kibanaversion
  register: version_output
  check_mode: no
  changed_when: no
- name: Copy PEM file to Kibana for secure ElasticSearch
  copy: src=/tmp/mapr_spyglass/es/sg/ca/es-root-ca.pem dest=/opt/mapr/kibana/kibana-{{ version_output.stdout }}/config/ca/ owner={{ mapr_user }} group={{ mapr_group }} mode=0600
- name: Copy Keystore Password
  copy: src=/tmp/mapr_spyglass/es/.keystore_password dest=/opt/mapr/kibana/kibana-{{ version_output.stdout }}/config/ owner={{ mapr_user }} group={{ mapr_group }} mode=0600
