---
# Enable NM local Dir for YARN Node Manager
- name: Check local dir for NodeManager
  shell: "maprcli volume info -name mapr.{{ ansible_fqdn }}.local.nm-local-dir -json"
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  register: maprcli_result
  failed_when: false
  changed_when: false
  check_mode: no
#- debug: var=maprcli_result
- name: Delete local dir for NodeManager if exists
  shell: "hadoop fs -rm -R /var/mapr/local/{{ ansible_fqdn }}/nm-local-dir"
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: maprcli_result.stdout is search("No such volume")
  failed_when: false
- name: Create local volume for NodeManager local Dir
  shell: maprcli volume create -name mapr.{{ ansible_fqdn }}.local.nm-local-dir -path /var/mapr/local/{{ ansible_fqdn }}/nm-local-dir -replication 1 -localvolumehost {{ ansible_fqdn }} -createparent true
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: maprcli_result.stdout is search("No such volume")
- name: Restart NodeManager
  shell: maprcli node services -name nodemanager -action stop -nodes {{ ansible_fqdn }}
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
  when: maprcli_result.stdout is search("No such volume")
